### ISSUE TITLE
qiniu region setting will affect upload url which leads to upload fail

### ISSUE THREAD

**Issue by YUFAN2GA** [kingname/MarkdownPicPicker#9]
Only qiniu pic bucket created in  China east region is using _up.qiniu.com_ which seems to be hard coded or by default adopted , but if users create bucket in any other region, will lead to upload failures like following :
 
> (None, text_body:{"error":"incorrect region, please use up-z1.qiniu.com"}, req_id:LSAAAMUw8BLzmLAU, LSAAAMUw8BLzmLAU, exception:None, status_code:400, error:incorrect region, please use up-z1.qiniu.com, _ResponseInfo__response:<Response [400]>, x_log:body;TBLMGR:1;RS:2;CFGG:4;UP:10/400;UP:11/400)
the url is already in your clipboard!

> (None, text_body:{"error":"incorrect region, please use up-z2.qiniu.com"}, req_id:LSAAAMUw8BLzmLAU, LSAAAMUw8BLzmLAU, exception:None, status_code:400, error:incorrect region, please use up-z1.qiniu.com, _ResponseInfo__response:<Response [400]>, x_log:body;TBLMGR:1;RS:2;CFGG:4;UP:10/400;UP:11/400)
the url is already in your clipboard!

**Comment by kingname** [comment]
Thanks for your issue.

Do you use the release version or the source code?
If you use the source code, then you can set Qiniu's config here: [https://github.com/kingname/MarkdownPicPicker/blob/master/config/config.ini](https://github.com/kingname/MarkdownPicPicker/blob/master/config/config.ini)

And in the code, I use Qiniu's library.  What the library need is the access key and secret key and the bucket name. I don't know if there is any difference in different region and I don't know where to set the region.

So, I suspect if the library I use may be outdate. Anyway, I will make sure what the problem is and reply hours later.

**Comment by YUFAN2GA** [comment]
I did use config.ini to use my own bucket, and now I created one in east China zone and it works.
check this
https://github.com/qiniu/js-sdk/issues/176

**Comment by kingname** [comment]
Thanks for telling me the reason. In the discussion of the same issue in js-sdk, I find someone says that  there is an entry point to set the region in the newest js-sdk version. I will check for Python's newest version.

**Comment by kingname** [comment]
I have read Qiniu's newest document for Python SDK, but there are not any words about the regions. 
So, maybe the most suitable solution is waiting and use the east China zone temporarily.

By the way, I have submitted a work order.

**Comment by kingname** [comment]
@YUFAN2GA Please update to the latest Qiniu's sdk and make a try. The zone problem has been fixed.
